# 系统配置
system:
  # 服务命令
  service-name: gin-web
  # 运行端口
  port: 8000
  # 运行模式，支持 debug 和 release
  mode: debug
  # API 前缀
  api-prefix: api
  # API 版本
  api-version: v1

# 日志配置
log:
  # 日志等级，参考 zapcore.Level（-1<=level<=5，-1 / DEBUG）
  level: -1
  # 是否输出颜色
  colorful: false
  # 日志路径
  path: logs
  # 日志大小，M
  max-size: 100
  # 日志备份数量
  max-backups: 10
  # 日志保留时间，天
  max-age: 30
  # 是否压缩
  compress: true

# MySQL 配置
mysql:
  # 主机地址，IP 或者解析的域名
  host: 192.168.200.10
  # 端口
  port: 3306
  # 数据库名称
  database: go-web
  # 数据库账户
  username: root
  # 数据库密码
  password: 123456
  # 编码
  charset: utf8mb4
  # 字符集
  collation: utf8mb4_general_ci
  # 连接串
  query: parseTime=True&loc=Local&timeout=10000ms
  # 表名前缀
  table-prefix: ""
  # 最大空闲连接数
  max-idle-connections: 10
  # 最大连接数
  max-open-connections: 100
  # 连接最大可复用时间，分钟
  max-idle-time: 60
  # 是否打印日志，false 只打印 Error
  log-mode: false
  # 日志级别(1-3，Info，Warn，Error)
  log-level: 1



